### PR TITLE
Fixes Ice Asteroid, Storm, and Laser Shooting

### LINKED ISSUE #40: Fix Laser

### LINKED ISSUE #43: Larger Ice Cloud

### LINKED ISSUE #44: Fix Blur

### PR DESCRIPTION
**Pull request by zahrarasoulifar**
Fixes #43 
Fixes #44 
Fixes #40 

Comment: Removed laser package example scenes.
Comment: Moved laser prefab to game manager.

-- Other comments are on external package codes --

### CODE REVIEW

File: Assets/Scripts/Model/PlayerShip.cs [hunk 1]
```diff
@@ -9,11 +9,11 @@ namespace Model
 	public class PlayerShip : Ship
 	{
 
-
-		public GameObject laserPrefab = null;
 		public GameObject laser = null;
-
+		public GameObject laserPrefab;
```
Comment (MajorTreble) [inline Assets/Scripts/Model/PlayerShip.cs:13]: The prefab should go on a controller/manager to Instantiate

File: Assets/Scripts/Model/PlayerShip.cs [hunk 2]
```diff
@@ -65,60 +65,72 @@ void GetWeapon()
...
+            if (isVisible)
+            {
+                RaycastHit hit;
+                Vector3 direction = laser.transform.forward;
+
+                if (Physics.Raycast(weapon_1.transform.position, direction, out hit, laserDist))
+                {
+                    if (hit.transform.CompareTag(this.transform.tag)) return;
+
+                    Ship ship = hit.transform.gameObject.GetComponent<Ship>();
```
Comment (MajorTreble) [inline Assets/Scripts/Model/PlayerShip.cs:98]: You can use an interface here like IDamagable with a method ReceiveDamage

File: Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/CannonBehavior.cs [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+	// Use this for initialization
+	void Start () 
+	{
+	
+	}
+	
+	// Update is called once per frame
+	void Update () 
+	{
+		if (Input.GetKey(KeyCode.LeftArrow))
```
Comment (MajorTreble) [inline Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/CannonBehavior.cs:20]: Inputs should go inside a controller

File: Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/ShotBehavior.cs [hunk 4]
```diff
@@ -0,0 +1,16 @@
+﻿using UnityEngine;
+using System.Collections;
+
+public class ShotBehavior : MonoBehaviour {
```
Comment (MajorTreble) [inline Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/ShotBehavior.cs:4]: What is this used for? Is it a missile?

**Comment by MajorTreble** [comment]
The example code is very similar to our gameplay code. I'm not sure we should submit it.

**Review by MajorTreble — CHANGES_REQUESTED** [review]
Example code

File: Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/ShotBehavior.cs (hunk 4 above)
Comment (zahrarasoulifar) [reply Assets/VolumetricLines/BuiltInRenderPipeline/ExampleScenes/ExampleScripts/ShotBehavior.cs:4]: This is a package. I used a package for the laser prefab. I didn't change package files.

**Review by MajorTreble — APPROVED** [review]
